from cd4ml.problems.zillow.readers.stream_zillow import float_or_zero, process_row


def test_float_or_zero():
    assert float_or_zero('5') == 5.0
    assert float_or_zero('-5') == -5.0
    assert float_or_zero('') == 0.0


def test_process_row():
    row_raw = {'parcelid': '17212207',
               'airconditioningtypeid': '',
               'architecturalstyletypeid': '',
               'basementsqft': '',
               'bathroomcnt': '2.0',
               'bedroomcnt': '5.0',
               'buildingclasstypeid': '',
               'buildingqualitytypeid': '',
               'calculatedbathnbr': '2.0',
               'decktypeid': '',
               'finishedfloor1squarefeet': '2085',
               'calculatedfinishedsquarefeet': '2085.0',
               'finishedsquarefeet12': '2085',
               'finishedsquarefeet13': '',
               'finishedsquarefeet15': '',
               'finishedsquarefeet50': '2085',
               'finishedsquarefeet6': '',
               'fips': '06111',
               'fireplacecnt': '1',
               'fullbathcnt': '2',
               'garagecarcnt': '2',
               'garagetotalsqft': '456',
               'hashottuborspa': '',
               'heatingorsystemtypeid': '',
               'latitude': '34199102',
               'longitude': '-118882964',
               'lotsizesquarefeet': '10800.0',
               'poolcnt': '1',
               'poolsizesum': '450',
               'pooltypeid10': '',
               'pooltypeid2': '',
               'pooltypeid7': '1',
               'propertycountylandusecode': '1111',
               'propertylandusetypeid': '261',
               'propertyzoningdesc': '',
               'rawcensustractandblock': '061110067.002012',
               'regionidcity': '34278',
               'regionidcounty': '2061',
               'regionidneighborhood': '',
               'regionidzip': '96383',
               'roomcnt': '9.0',
               'storytypeid': '',
               'threequarterbathnbr': '',
               'typeconstructiontypeid': '',
               'unitcnt': '',
               'yardbuildingsqft17': '',
               'yardbuildingsqft26': '',
               'yearbuilt': '1962.0',
               'numberofstories': '1',
               'fireplaceflag': '',
               'structuretaxvaluedollarcnt': '230000.0',
               'taxvaluedollarcnt': '657000.0',
               'assessmentyear': '2015',
               'landtaxvaluedollarcnt': '427000.0',
               'taxamount': '6991.06',
               'taxdelinquencyflag': '',
               'taxdelinquencyyear': '',
               'censustractandblock': '61110067002012',
               'transaction_date': '2016-03-17',
               'logerror': '0.0834'}

    result = process_row(row_raw)

    expected = {'airconditioningtypeid': '',
                'architecturalstyletypeid': '',
                'buildingqualitytypeid': '',
                'buildingclasstypeid': '',
                'decktypeid': '',
                'threequarterbathnbr': '',
                'fips': '06111',
                'fireplaceflag': '',
                'hashottuborspa': '',
                'heatingorsystemtypeid': '',
                'parcelid': '17212207',
                'pooltypeid10': '',
                'pooltypeid2': '',
                'pooltypeid7': '1',
                'propertycountylandusecode': '1111',
                'propertylandusetypeid': '261',
                'propertyzoningdesc': '',
                'rawcensustractandblock': '061110067.002012',
                'censustractandblock': '61110067002012',
                'regionidcounty': '2061',
                'regionidcity': '34278',
                'regionidzip': '96383',
                'regionidneighborhood': '',
                'storytypeid': '',
                'typeconstructiontypeid': '',
                'taxdelinquencyflag': '',
                'transaction_date': '2016-03-17',
                'basementsqft': 0.0,
                'bathroomcnt': 2.0,
                'bedroomcnt': 5.0,
                'calculatedbathnbr': 2.0,
                'finishedfloor1squarefeet': 2085.0,
                'calculatedfinishedsquarefeet': 2085.0,
                'finishedsquarefeet6': 0.0,
                'finishedsquarefeet12': 2085.0,
                'finishedsquarefeet13': 0.0,
                'finishedsquarefeet15': 0.0,
                'finishedsquarefeet50': 2085.0,
                'fireplacecnt': 1.0,
                'fullbathcnt': 2.0,
                'garagecarcnt': 2.0,
                'garagetotalsqft': 456.0,
                'latitude': 34199102.0,
                'longitude': -118882964.0,
                'lotsizesquarefeet': 10800.0,
                'numberofstories': 1.0,
                'poolcnt': 1.0,
                'poolsizesum': 450.0,
                'roomcnt': 9.0,
                'unitcnt': 0.0,
                'yardbuildingsqft17': 0.0,
                'yardbuildingsqft26': 0.0,
                'yearbuilt': 1962.0,
                'taxvaluedollarcnt': 657000.0,
                'structuretaxvaluedollarcnt': 230000.0,
                'landtaxvaluedollarcnt': 427000.0,
                'taxamount': 6991.06,
                'assessmentyear': 2015.0,
                'taxdelinquencyyear': 0.0,
                'logerror': 0.0834}

    assert result == expected

