FROM jenkins/jenkins:2.230-slim

USER jenkins
RUN /usr/local/bin/install-plugins.sh blueocean:1.22.0 build-timestamp:1.0.3 timestamper:1.11.2 pollscm:1.3.1 github-api:1.106

USER root
ENV FLUENTD_HOST "fluentd"
ENV FLUENTD_PORT "24224"
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false
ENV JENKINS_URL "http://jenkins:10000"

RUN apt update && \
    apt install -y python3 python3-pip

COPY ./requirements.txt requirements.txt
COPY jenkins/1-configureJenkins.groovy /usr/share/jenkins/ref/init.groovy.d/1-configureJenkins.groovy
RUN pip3 install -r requirements.txt