FROM jenkins/jenkins:lts

USER root

RUN apt update && \
    apt install -y python3 python3-pip docker 

RUN echo "dvc[gs]==0.71.0" >> requirements.txt && \
    echo "numpy==1.17.4" >> requirements.txt && \
    echo "pandas==0.25.3" >> requirements.txt && \
    echo "pylint==2.4.4" >> requirements.txt && \
    echo "pytest==5.3.0" >> requirements.txt && \
    echo "scikit-learn==0.21.3" >> requirements.txt && \
    echo "flask==1.1.1" >> requirements.txt && \
    echo "mlflow==1.4.0" >> requirements.txt && \
    echo "lime==0.1.1.36" >> requirements.txt && \
    echo "fluent-logger==0.9.4" >> requirements.txt && \
    echo "s3fs==0.1.2" >> requirements.txt && \
    echo "seaborn==0.9.0" >> requirements.txt && \
    echo "joblib==0.14.0" >> requirements.txt

RUN pip3 install -r requirements.txt