FROM python:3.7-slim-buster
WORKDIR /usr/src/app

RUN pip install awscli boto3 mlflow==1.10.0
EXPOSE 5000
ENV MLFLOW_S3_ENDPOINT_URL ${MLFLOW_S3_ENDPOINT_URL}
ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENTRYPOINT mlflow server -h 0.0.0.0 -p 5000 --default-artifact-root s3://cd4ml-ml-flow-bucket/ --backend-store-uri /mnt/mlflow